# Generated by Django 6.0.1 on 2026-01-08 16:38

import apps.academico.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Está activo')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[apps.academico.validators.validate_nombre_no_vacio, apps.academico.validators.validate_nombre_sin_caracteres_especiales, apps.academico.validators.validate_longitud_minima_nombre], verbose_name='Nombre de la modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Está activo')),
                ('nombre', models.CharField(max_length=150, unique=True, validators=[apps.academico.validators.validate_nombre_no_vacio, apps.academico.validators.validate_nombre_sin_caracteres_especiales, apps.academico.validators.validate_longitud_minima_nombre], verbose_name='Nombre de la carrera')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academico.modalidad', verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
    ]
