# Generated by Django 6.0.1 on 2026-01-08 16:59

import apps.academico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, validators=[apps.academico.validators.validate_nombre_no_vacio, apps.academico.validators.validate_nombre_sin_caracteres_especiales, apps.academico.validators.validate_longitud_minima_nombre, apps.academico.validators.validate_nombre_alfanumerico], verbose_name='Nombre de la carrera'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[apps.academico.validators.validate_nombre_no_vacio, apps.academico.validators.validate_nombre_sin_caracteres_especiales, apps.academico.validators.validate_longitud_minima_nombre, apps.academico.validators.validate_nombre_alfanumerico], verbose_name='Nombre de la modalidad'),
        ),
    ]
