# Generated by Django 6.0.1 on 2026-01-08 17:25

import apps.academico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_carrera_nombre_alter_modalidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=150, validators=[apps.academico.validators.validate_nombre_no_vacio, apps.academico.validators.validate_nombre_sin_caracteres_especiales, apps.academico.validators.validate_longitud_minima_nombre, apps.academico.validators.validate_nombre_alfanumerico], verbose_name='Nombre de la carrera'),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('nombre', 'modalidad')},
        ),
    ]
