# Generated by Django 5.0 on 2026-01-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_carrera_nombre_alter_carrera_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together=set(),
        ),
    ]
